ovl/podman: Add CDI tools

diff --git a/ovl/podman/tar b/ovl/podman/tar
--- a/ovl/podman/tar
+++ b/ovl/podman/tar
@@ -41,6 +41,12 @@ f=$SRIOV_DIR/build/sriov
 test -x $f && cp $f $tmp/opt/cni/bin
 echo "Installed sriov CNI"
 
+test -n "$CDI_DIR" || \
+	CDI_DIR=$GOPATH/src/github.com/cncf-tags/container-device-interface
+make -C $CDI_DIR > /dev/null 2>&1 || die "Cannot make CDI tools"
+cp -R $CDI_DIR/bin/* $tmp/bin
+echo "Installed CDI tools"
+
 cd $tmp
 tar cf "$1" *
 cd - > /dev/null
