ovl/ovs; fix noarp

diff --git a/ovl/ovs/default/bin/ovs_test b/ovl/ovs/default/bin/ovs_test
--- a/ovl/ovs/default/bin/ovs_test
+++ b/ovl/ovs/default/bin/ovs_test
@@ -102,6 +102,14 @@ cmd_add_vip() {
 	done
 }
 
+##   noarp [interfaces...]
+cmd_noarp() {
+	local iface
+	for iface in $@; do
+		ip link set arp off $iface || die "Failed noarp on [$iface]"
+	done
+}
+
 ##
 ## Test cases;
 ##   version - Log versions
