ovl/netns; isolated bridges

diff --git a/ovl/netns/default/bin/netns_test b/ovl/netns/default/bin/netns_test
--- a/ovl/netns/default/bin/netns_test
+++ b/ovl/netns/default/bin/netns_test
@@ -202,7 +202,7 @@ cmd_for() {
 cmd_name() {
 	local n
 	for n in $(cmd_for $1 $2); do
-		printf "%s-ns%02d\n" $(hostname) $n
+		printf "${NAME_PREFIX}%s-ns%02d\n" $(hostname) $n
 	done
 }
 
@@ -502,6 +502,62 @@ cmd_tcase_ping_all_pods() {
 		done
 	done
 }
+##   tcase_xbridge <bridge> <external_interface>
+##     Create a bridge with external access.
+cmd_tcase_xbridge() {
+	tcase "Xternal bridge; $1 iface $2"
+	test -n "$2" || die "Parameter missing"
+	local br=$1
+	local dev=$2
+
+	NAME_PREFIX=$1-
+	cmd_tcase_create_with_addresses
+
+	ip link add name $br type bridge || tdie
+	sysctl -qw net.ipv6.conf.$br.accept_dad=0 || die
+	sysctl -qw net.ipv6.conf.$br.accept_ra=0 || die
+	ip link set up dev $br || die
+	cmd_connect_to_bridge $br
+
+	sysctl -qw net.ipv6.conf.$dev.accept_dad=0 || die
+	sysctl -qw net.ipv6.conf.$dev.accept_ra=0 || die
+	ip link set up dev $dev || die
+	ip link set dev $dev master $br || tdie
+}
+##   tcase_xnetns [interfaces...]
+##     Move interfaces to netns'es and set addresses
+cmd_tcase_xnetns() {
+	tcase "Move interfaces to netns'es [$@]"
+	local iface name adr
+	local mynode=$(mynode)
+	mkdir -p /var/run/utsns
+	for iface in $@; do
+		name=$(hostname)-$iface
+		ip netns add $name || die
+		touch /var/run/utsns/$name
+		unshare --net=/var/run/netns/$name --uts=/var/run/utsns/$name \
+			$me init $name
+
+		ip link set dev $iface netns $name || tdie
+		ip -n $name link set up dev $iface
+		adr=$(ipu makeip --cidr=$ADRTEMPLATE --subnet=2 --host=100)
+		ip -n $name addr add $adr dev $iface
+		adr=$(ipu makeip --cidr=$ADRTEMPLATE --subnet=2 --host=100 --ipv6template=1000::1:0.0.0.0)
+		ip -6 -n $name addr add $adr dev $iface
+	done
+}
+##   tcase_create_vlans [interfaces...]
+##     Create vlan interfaces
+cmd_tcase_create_vlans() {
+	tcase "Create vlan interfaces [$@]"
+	local master vlan dev
+	for dev in $@; do
+		master=$(echo $dev | cut -d. -f1)
+		vlan=$(echo $dev | cut -d. -f2)
+		ip link add link $master name $dev type vlan id $vlan || tdie
+	done
+}
+
 
 test -r /usr/lib/xctest && . /usr/lib/xctest
 indent='  '
