ovl/iperf; Prepare for K8s bandwidth limitation tests

diff --git a/ovl/iperf/image/tar b/ovl/iperf/image/tar
--- a/ovl/iperf/image/tar
+++ b/ovl/iperf/image/tar
@@ -1,30 +1,27 @@
 #! /bin/sh
+# NOTE: A common pattern is to specify "-" (stdout) as out-file,
+#  so there must be NO log printouts to stdout!
 
 dir=$(dirname $0); dir=$(readlink -f $dir)
 tmp=/tmp/$USER/xcluster_$$
 die() {
-    echo "ERROR: $*" >&2
-    rm -rf $tmp
-    exit 1
+	echo "ERROR: $*" >&2
+	rm -rf $tmp
+	exit 1
 }
 log() {
-    echo "INFO: $*" >&2
+	echo "INFO: $*" >&2
 }
 
 test -n "$1" || die "No out-file"
 
 mkdir -p $tmp/bin
+#cp -R $dir/default/* $tmp
 
-prg=$XCLUSTER_WORKSPACE/iperf-2.0.12/src/iperf
-test -x $prg || die "Not executable [$prg]"
-cp $prg $tmp/bin/iperf2
-
-prg=$GOPATH/src/github.com/esnet/iperf/src/iperf3
-test -x $prg || die "Not executable [$prg]"
-cp $prg $tmp/bin/iperf3
-
-$XCLUSTER cplib --dest=$tmp $tmp/bin/*
-$XCLUSTER cploader --dest=$tmp $tmp
+test -n "$IPERF_WORKSPACE" || IPERF_WORKSPACE=/tmp/$USER/iperf
+x=$IPERF_WORKSPACE/bin/iperf
+test -x $x || die "Not executable [$x]"
+cp $x $tmp/bin
 
 cd $tmp
 tar cf "$1" *
